### ISSUE TITLE
ValueError with Negative Parameter Values

### ISSUE THREAD

**Issue by Willcarr99** [dubiousbreakfast/pfunk#3]
I've come across an issue whenever I have one or more negative potential parameter values in my input file. This happens, for example, using Liang et. al (2009)'s global 3He OMP, where the imaginary spin-orbit depth parameter is defined as the constant -1.1591 MeV.

When calling the `run_anneal()` method in the `model_fit.MAPFit()` class with an input file containing at least one negative parameter, I get the error message: "ValueError: Bounds are not consistent min < max", coming from line 149 of model_fit.py. This is the `opt.dual_annealing(..., bnds, ...)` call, where opt is scipy.optimize and bnds is defined by lines 147: `low, up = self.set_bounds(self.percent_range, bnds=False)` and 148: `bnds = [(i,j) for i,j in zip(low,up)]`. When dealing with negative parameters, the `set_bounds()` method appears to assign the variable "lower" to the upper value and "upper" to the lower value:

`upper = []`
`lower = []`
`for ele in self.x0:`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`lower.append(ele - (percent*ele))`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`upper.append(ele + (percent*ele))`

e.g. With ele = -1.1591 and percent = 0.2, upper = -1.39092 and lower = -0.92728, but upper is really the smaller value and vice versa, so `opt.dual_annealing(..., bnds, ...)` raises the ValueError described above.

A solution would be to replace `lower.append(ele - (percent*ele))` with `lower.append(ele - (percent*abs(ele)))` and replace `upper.append(ele + (percent*ele))` with `upper.append(ele + (percent*abs(ele)))` in `set_bounds()`.

This issue presumably also occurs using some other run methods besides `run_anneal()`, but the solution mentioned appears to correct them all (although I haven't tested this).

**Comment by camarsha** [comment]
Thanks for bringing this up, it has been an issue for a long time that I kept working around instead of fixing. I'll implement your solution and push the update in the next few days.
